<a href="https://colab.research.google.com/github/PrettyHan/Elice_2/blob/master/Week13_2_Pandas_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2. Pandas

code source : https://www.kaggle.com/learn/pandas

data soucre : https://www.kaggle.com/code/residentmario/creating-reading-and-writing/data

### 2-1. Creating, Reading, and Writing

### 2-2. Indexing, Selecting & Assigning

### 2-3. Summary Fuctions and Maps

### 2-4. Grouping and Sorting

### 2-5. Data Types and Missing Values

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd

## 2-1. Creating Reading, and Writing

### 2-1-1. Creating Data

In [ ]:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [ ]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [ ]:
pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 
              'Sue': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

### 2-1-2. Series

In [ ]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

# 2-1-3. Reading data files

In [ ]:
df = pd.read_csv("./winemag-data-10k-v2.csv")

In [ ]:
df.shape

(10000, 14)

In [ ]:
df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [ ]:
reviews = pd.read_csv("./winemag-data-10k-v2.csv", index_col=0)
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks


## 2-2. Indexing, Selecting & Assigning

In [ ]:
reviews.country

0          Italy
1       Portugal
2             US
3             US
4             US
          ...
9995          US
9996          US
9997      France
9998          US
9999      France
Name: country, Length: 10000, dtype: object

In [ ]:
reviews['country']

0          Italy
1       Portugal
2             US
3             US
4             US
          ...
9995          US
9996          US
9997      France
9998          US
9999      France
Name: country, Length: 10000, dtype: object

In [ ]:
reviews['country'][0]

'Italy'

In [ ]:
reviews.iloc[0]

country                                                              Italy
description              Aromas include tropical fruit, broom, brimston...
designation                                                   Vulkà Bianco
points                                                                  87
price                                                                  NaN
province                                                 Sicily & Sardinia
region_1                                                              Etna
region_2                                                               NaN
taster_name                                                  Kerin O’Keefe
taster_twitter_handle                                         @kerinokeefe
title                                    Nicosia 2013 Vulkà Bianco  (Etna)
variety                                                        White Blend
winery                                                             Nicosia
Name: 0, dtype: object

In [ ]:
reviews.iloc[:, 0]

0          Italy
1       Portugal
2             US
3             US
4             US
          ...
9995          US
9996          US
9997      France
9998          US
9999      France
Name: country, Length: 10000, dtype: object

In [ ]:
reviews.iloc[:3, 0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [ ]:
reviews.iloc[[0, 1, 2], 0]

0       Italy
1    Portugal
2          US
Name: country, dtype: object

In [ ]:
reviews.loc[0, 'country']

'Italy'

In [ ]:
reviews.loc[:, ['taster_name', 'taster_twitter_handle', 'points']]

             taster_name taster_twitter_handle  points
0          Kerin O’Keefe          @kerinokeefe      87
1             Roger Voss            @vossroger      87
2           Paul Gregutt           @paulgwine       87
3     Alexander Peartree                   NaN      87
4           Paul Gregutt           @paulgwine       87
...                  ...                   ...     ...
9995                 NaN                   NaN      89
9996        Paul Gregutt           @paulgwine       89
9997          Roger Voss            @vossroger      89
9998                 NaN                   NaN      91
9999          Roger Voss            @vossroger      91

[10000 rows x 3 columns]

In [ ]:
reviews.country == 'Italy'

0        True
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: country, Length: 10000, dtype: bool

In [ ]:
reviews.loc[reviews.country == 'Italy']

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9976,Italy,Subdued aromas of Spanish broom and brimstone ...,Animalucente Bianco,87,45.0,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Contrada Santo Spirito di Passopisciaro 2012 A...,White Blend,Contrada Santo Spirito di Passopisciaro
9980,Italy,"Here's a plush, modern and thickly extracted B...",Vigne Vecchie,89,NaN,Piedmont,Barbera d'Asti Superiore,NaN,NaN,NaN,Vinchio-Vaglio Serra 2007 Vigne Vecchie (Barb...,Barbera,Vinchio-Vaglio Serra
9987,Italy,Here's a sweet and luscious Barbera d'Alba wit...,Giuli,89,NaN,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Cascina Ballarin 2007 Giuli (Barbera d'Alba),Barbera,Cascina Ballarin
9988,Italy,"Thick, black and extracted, this dense Barbera...",Del Beneficio,89,NaN,Piedmont,Barbera d'Asti Superiore,NaN,NaN,NaN,Castello di Razzano 2007 Del Beneficio (Barbe...,Barbera,Castello di Razzano
9989,Italy,Pretty coffee notes are offset by ripe aromas ...,La Tota,89,28.0,Piedmont,Barbera d'Asti,NaN,NaN,NaN,Marchesi Alfieri 2007 La Tota (Barbera d'Asti),Barbera,Marchesi Alfieri

In [ ]:
reviews.loc[(reviews.country == 'Italy') & (reviews.points >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
133,Italy,"Einaudi's wines have been improving lately, an...",NaN,91,68.0,Piedmont,Barolo,NaN,NaN,NaN,Poderi Luigi Einaudi 2003 Barolo,Nebbiolo,Poderi Luigi Einaudi
135,Italy,The color is just beginning to show signs of b...,Sorano,91,60.0,Piedmont,Barolo,NaN,NaN,NaN,Giacomo Ascheri 2001 Sorano (Barolo),Nebbiolo,Giacomo Ascheri
140,Italy,"A big, fat, luscious wine with plenty of toast...",Costa Bruna,90,26.0,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Poderi Colla 2005 Costa Bruna (Barbera d'Alba),Barbera,Poderi Colla
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9711,Italy,"Scorched earth, black-skinned berry, orange ze...",Nervo Vigna Giaia Riserva,90,50.0,Piedmont,Barbaresco,NaN,Kerin O’Keefe,@kerinokeefe,Piazzo Armando 2010 Nervo Vigna Giaia Riserva ...,Nebbiolo,Piazzo Armando
9730,Italy,"This opens with aromas of ripe, dark-skinned b...",Sanadaive,90,NaN,Piedmont,Barbaresco,NaN,Kerin O’Keefe,@kerinokeefe,Adriano Marco & Vittorio 2012 Sanadaive (Barb...,Nebbiolo,Adriano Marco & Vittorio
9731,Italy,"This opens with aromas of red berry, underbrus...",Ronchi,90,50.0,Piedmont,Barbaresco,NaN,Kerin O’Keefe,@kerinokeefe,Albino Rocca 2012 Ronchi (Barbaresco),Nebbiolo,Albino Rocca
9816,Italy,"Forest floor, new leather, ripe, dark-skinned ...",Riserva,93,39.0,Tuscany,Chianti Classico,NaN,Kerin O’Keefe,@kerinokeefe,Badia a Coltibuono 2011 Riserva (Chianti Clas...,Red Blend,Badia a Coltibuono
9934,Italy,"Almond blossom, stone fruit and a tiny touch o...",Extra Dry Particella 68,90,NaN,Veneto,Prosecco di Valdobbiadene,NaN,NaN,NaN,Sorelle Bronca NV Extra Dry Particella 68 (Pr...,Prosecco,Sorelle Bronca

In [ ]:
reviews.loc[(reviews.country == 'Italy') | (reviews.points >= 90)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
13,Italy,This is dominated by oak and oak-driven aromas...,Rosso,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Masseria Setteporte 2012 Rosso (Etna),Nerello Mascalese,Masseria Setteporte
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Baglio di Pianetto 2007 Ficiligno White (Sicilia),White Blend,Baglio di Pianetto
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0,Sicily & Sardinia,Sicilia,NaN,Kerin O’Keefe,@kerinokeefe,Canicattì 2009 Aynat Nero d'Avola (Sicilia),Nero d'Avola,Canicattì
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,Italy,Here's a sweet and luscious Barbera d'Alba wit...,Giuli,89,NaN,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Cascina Ballarin 2007 Giuli (Barbera d'Alba),Barbera,Cascina Ballarin
9988,Italy,"Thick, black and extracted, this dense Barbera...",Del Beneficio,89,NaN,Piedmont,Barbera d'Asti Superiore,NaN,NaN,NaN,Castello di Razzano 2007 Del Beneficio (Barbe...,Barbera,Castello di Razzano
9989,Italy,Pretty coffee notes are offset by ripe aromas ...,La Tota,89,28.0,Piedmont,Barbera d'Asti,NaN,NaN,NaN,Marchesi Alfieri 2007 La Tota (Barbera d'Asti),Barbera,Marchesi Alfieri
9998,US,It's interesting and a little odd that this 10...,To Kalon Vineyard I Block,91,75.0,California,Oakville,Napa,NaN,NaN,Robert Mondavi 2010 To Kalon Vineyard I Block ...,Fumé Blanc,Robert Mondavi
9999,France,"As befits a single vineyard Gevrey Chambertin,...",Les Evocelles,91,52.0,Burgundy,Gevrey-Chambertin,NaN,Roger Voss,@vossroger,Henri de Villamont 2010 Les Evocelles (Gevrey...,Pinot Noir,Henri de Villamont

In [ ]:
reviews.loc[reviews.country.isin(['Italy', 'France'])]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
6,Italy,"Here's a bright, informal red that opens with ...",Belsito,87,16.0,Sicily & Sardinia,Vittoria,NaN,Kerin O’Keefe,@kerinokeefe,Terre di Giurfo 2013 Belsito Frappato (Vittoria),Frappato,Terre di Giurfo
7,France,This dry and restrained wine offers spice in p...,NaN,87,24.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Trimbach 2012 Gewurztraminer (Alsace),Gewürztraminer,Trimbach
9,France,This has great depth of flavor with its fresh ...,Les Natures,87,27.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,Pinot Gris,Jean-Baptiste Adam
11,France,"This is a dry wine, very spicy, with a tight, ...",NaN,87,30.0,Alsace,Alsace,NaN,Roger Voss,@vossroger,Leon Beyer 2012 Gewurztraminer (Alsace),Gewürztraminer,Leon Beyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9987,Italy,Here's a sweet and luscious Barbera d'Alba wit...,Giuli,89,NaN,Piedmont,Barbera d'Alba,NaN,NaN,NaN,Cascina Ballarin 2007 Giuli (Barbera d'Alba),Barbera,Cascina Ballarin
9988,Italy,"Thick, black and extracted, this dense Barbera...",Del Beneficio,89,NaN,Piedmont,Barbera d'Asti Superiore,NaN,NaN,NaN,Castello di Razzano 2007 Del Beneficio (Barbe...,Barbera,Castello di Razzano
9989,Italy,Pretty coffee notes are offset by ripe aromas ...,La Tota,89,28.0,Piedmont,Barbera d'Asti,NaN,NaN,NaN,Marchesi Alfieri 2007 La Tota (Barbera d'Asti),Barbera,Marchesi Alfieri
9997,France,The style at Domaines Ott has changed to becom...,Château de Selle,89,43.0,Provence,Côtes de Provence,NaN,Roger Voss,@vossroger,Domaines Ott 2009 Château de Selle Rosé (Côtes...,Rosé,Domaines Ott
9999,France,"As befits a single vineyard Gevrey Chambertin,...",Les Evocelles,91,52.0,Burgundy,Gevrey-Chambertin,NaN,Roger Voss,@vossroger,Henri de Villamont 2010 Les Evocelles (Gevrey...,Pinot Noir,Henri de Villamont

In [ ]:
reviews.loc[reviews.price.notnull()]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
5,Spain,Blackberry and raspberry aromas show a typical...,Ars In Vitro,87,15.0,Northern Spain,Navarra,NaN,Michael Schachner,@wineschach,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,Tempranillo-Merlot,Tandem
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,US,Comes from a little-understood part of the spr...,Griffin's Lair,89,46.0,California,Sonoma Coast,Sonoma,NaN,NaN,Roessler 2008 Griffin's Lair Pinot Noir (Sonom...,Pinot Noir,Roessler
9996,US,"Smoky and savory, with sharp acidity under bla...",NaN,89,22.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Seven Hills 2007 Tempranillo (Columbia Valley ...,Tempranillo,Seven Hills
9997,France,The style at Domaines Ott has changed to becom...,Château de Selle,89,43.0,Provence,Côtes de Provence,NaN,Roger Voss,@vossroger,Domaines Ott 2009 Château de Selle Rosé (Côtes...,Rosé,Domaines Ott
9998,US,It's interesting and a little odd that this 10...,To Kalon Vineyard I Block,91,75.0,California,Oakville,Napa,NaN,NaN,Robert Mondavi 2010 To Kalon Vineyard I Block ...,Fumé Blanc,Robert Mondavi
9999,France,"As befits a single vineyard Gevrey Chambertin,...",Les Evocelles,91,52.0,Burgundy,Gevrey-Chambertin,NaN,Roger Voss,@vossroger,Henri de Villamont 2010 Les Evocelles (Gevrey...,Pinot Noir,Henri de Villamont

In [ ]:
reviews['critic'] = 'everyone'
reviews['critic']

0       everyone
1       everyone
2       everyone
3       everyone
4       everyone
          ...
9995    everyone
9996    everyone
9997    everyone
9998    everyone
9999    everyone
Name: critic, Length: 10000, dtype: object

In [ ]:
reviews['index_backwards'] = range(len(reviews), 0, -1)
reviews['index_backwards']

0       10000
1        9999
2        9998
3        9997
4        9996
        ...
9995        5
9996        4
9997        3
9998        2
9999        1
Name: index_backwards, Length: 10000, dtype: int64

### 2-3. Summary Fuctions and Maps

In [ ]:
reviews.points.describe()

count    10000.000000
mean        88.395700
std          3.010752
min         80.000000
25%         86.000000
50%         88.000000
75%         90.000000
max        100.000000
Name: points, dtype: float64

In [ ]:
reviews.points.mean()

88.3957

In [ ]:
reviews.taster_name.unique()

array(['Kerin O’Keefe', 'Roger Voss', 'Paul Gregutt',
       'Alexander Peartree', 'Michael Schachner', 'Anna Lee C. Iijima',
       'Virginie Boone', 'Matt Kettmann', nan, 'Sean P. Sullivan',
       'Jim Gordon', 'Joe Czerwinski', 'Anne Krebiehl\xa0MW',
       'Lauren Buzzeo', 'Mike DeSimone', 'Jeff Jenssen',
       'Susan Kostrzewa', 'Carrie Dykes', 'Fiona Adams'], dtype=object)

In [ ]:
reviews.taster_name.value_counts()

Roger Voss            1943
Michael Schachner     1216
Kerin O’Keefe          865
Virginie Boone         785
Paul Gregutt           707
Matt Kettmann          483
Joe Czerwinski         399
Sean P. Sullivan       372
Jim Gordon             337
Anna Lee C. Iijima     308
Anne Krebiehl MW       230
Lauren Buzzeo          139
Susan Kostrzewa        111
Alexander Peartree      41
Jeff Jenssen            39
Mike DeSimone           34
Carrie Dykes             6
Fiona Adams              3
Name: taster_name, dtype: int64

In [ ]:
review_points_mean = reviews.points.mean()
reviews.points.map(lambda p: p - review_points_mean)

0      -1.3957
1      -1.3957
2      -1.3957
3      -1.3957
4      -1.3957
         ...
9995    0.6043
9996    0.6043
9997    0.6043
9998    2.6043
9999    2.6043
Name: points, Length: 10000, dtype: float64

In [ ]:
def remean_points(row):
    row.points = row.points - review_points_mean
    return row

reviews.apply(remean_points, axis='columns').head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,-1.3957,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,10000
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,-1.3957,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos,everyone,9999
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,-1.3957,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm,everyone,9998
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,-1.3957,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian,everyone,9997
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,-1.3957,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks,everyone,9996

In [ ]:
reviews.head(1)

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia,everyone,10000

In [ ]:
review_points_mean = reviews.points.mean()
reviews.points - review_points_mean

0      -1.3957
1      -1.3957
2      -1.3957
3      -1.3957
4      -1.3957
         ...
9995    0.6043
9996    0.6043
9997    0.6043
9998    2.6043
9999    2.6043
Name: points, Length: 10000, dtype: float64

In [ ]:
reviews.country + " - " + reviews.region_1

0                     Italy - Etna
1                              NaN
2           US - Willamette Valley
3         US - Lake Michigan Shore
4           US - Willamette Valley
                   ...
9995             US - Sonoma Coast
9996     US - Columbia Valley (WA)
9997    France - Côtes de Provence
9998                 US - Oakville
9999    France - Gevrey-Chambertin
Length: 10000, dtype: object

### 2-4. Grouping and Sorting

In [ ]:
reviews.groupby('points').points.count()

points
80       16
81       42
82      129
83      274
84      450
85      786
86      999
87     1424
88     1341
89      934
90     1116
91      711
92      828
93      514
94      244
95      122
96       42
97       18
98        6
99        2
100       2
Name: points, dtype: int64

In [ ]:
reviews.groupby('points').price.min()

points
80       8.0
81       7.0
82       6.0
83       5.0
84       5.0
85       4.0
86       5.0
87       6.0
88       7.0
89       8.0
90       8.0
91      12.0
92      13.0
93      13.0
94      18.0
95      20.0
96      29.0
97      50.0
98      50.0
99      94.0
100    210.0
Name: price, dtype: float64

In [ ]:
reviews.groupby('winery').apply(lambda df: df.title.iloc[0])

winery
12 Linajes                   12 Linajes 2009 Reserva  (Ribera del Duero)
14 Hands                             14 Hands 2010 Riesling (Washington)
181                                               181 2008 Merlot (Lodi)
18401 Cellars          18401 Cellars 2013 Cabernet Sauvignon (Walla W...
1912 Winemakers        1912 Winemakers 2011 Vinhas Velhas Branco Whit...
                                             ...
Ànima Negra            Ànima Negra 2004 Àn Red (Vi de la Terra Illes ...
Árido                    Árido 2013 Sustainably Farmed Moscato (Mendoza)
Écluse                           Écluse 2014 Rendition Red (Paso Robles)
Ökonomierat Rebholz    Ökonomierat Rebholz 2007 Von Rotliegenden Spät...
àMaurice               àMaurice 2013 Fred Estate Syrah (Walla Walla V...
Length: 5487, dtype: object

In [ ]:
reviews.groupby(['country']).price.agg([len, min, max])

In [ ]:
reviews.sort_values(by='country', ascending = False).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
6969,Uruguay,Tarry grit and char are the lead aromas on thi...,Eolo Gran Reserva,86,23.0,Atlantida,NaN,NaN,Michael Schachner,@wineschach,Viñedo de los Vientos 2012 Eolo Gran Reserva R...,Red Blend,Viñedo de los Vientos,everyone,3031
9133,Uruguay,This mature Bordeaux-style blend is earthy on ...,Preludio Barrel Select Lote N 77,90,45.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2004 Preludio Barrel Select Lot...,Red Blend,Familia Deicas,everyone,867
4104,Uruguay,Cherry-berry aromas are floral but also a bit ...,Tannat-Merlot-Zinfandel,86,16.0,Canelones,NaN,NaN,Michael Schachner,@wineschach,Artesana 2013 Tannat-Merlot-Zinfandel Red (Can...,Red Blend,Artesana,everyone,5896
4051,Uruguay,Ripe earthy aromas of raisin and oaky vanilla ...,B2 Parcela Unica,88,43.0,Canelones,NaN,NaN,Michael Schachner,@wineschach,Bouza 2013 B2 Parcela Unica Tannat (Canelones),Tannat,Bouza,everyone,5949
6005,Uruguay,Ripe berry and prune aromas are accented by li...,Roble,90,35.0,Uruguay,NaN,NaN,Michael Schachner,@wineschach,Narbona 2013 Roble Tannat (Uruguay),Tannat,Narbona,everyone,3995

In [ ]:
reviews.sort_values(by=['country', 'points'], ascending = False).head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
6005,Uruguay,Ripe berry and prune aromas are accented by li...,Roble,90,35.0,Uruguay,NaN,NaN,Michael Schachner,@wineschach,Narbona 2013 Roble Tannat (Uruguay),Tannat,Narbona,everyone,3995
9133,Uruguay,This mature Bordeaux-style blend is earthy on ...,Preludio Barrel Select Lote N 77,90,45.0,Juanico,NaN,NaN,Michael Schachner,@wineschach,Familia Deicas 2004 Preludio Barrel Select Lot...,Red Blend,Familia Deicas,everyone,867
4051,Uruguay,Ripe earthy aromas of raisin and oaky vanilla ...,B2 Parcela Unica,88,43.0,Canelones,NaN,NaN,Michael Schachner,@wineschach,Bouza 2013 B2 Parcela Unica Tannat (Canelones),Tannat,Bouza,everyone,5949
4104,Uruguay,Cherry-berry aromas are floral but also a bit ...,Tannat-Merlot-Zinfandel,86,16.0,Canelones,NaN,NaN,Michael Schachner,@wineschach,Artesana 2013 Tannat-Merlot-Zinfandel Red (Can...,Red Blend,Artesana,everyone,5896
6969,Uruguay,Tarry grit and char are the lead aromas on thi...,Eolo Gran Reserva,86,23.0,Atlantida,NaN,NaN,Michael Schachner,@wineschach,Viñedo de los Vientos 2012 Eolo Gran Reserva R...,Red Blend,Viñedo de los Vientos,everyone,3031

# Quiz

1. Which country has the highest average of points?
2. In Italy, which taster gave the lowest average points?
3. Which winery has the highest average points?

### 2-5. Data Types and Missing Values

In [ ]:
reviews.price.dtype

dtype('float64')

In [ ]:
reviews.dtypes

country                   object
description               object
designation               object
points                     int64
price                    float64
province                  object
region_1                  object
region_2                  object
taster_name               object
taster_twitter_handle     object
title                     object
variety                   object
winery                    object
critic                    object
index_backwards            int64
dtype: object

In [ ]:
reviews.points.astype('float64')

0       87.0
1       87.0
2       87.0
3       87.0
4       87.0
        ...
9995    89.0
9996    89.0
9997    89.0
9998    91.0
9999    91.0
Name: points, Length: 10000, dtype: float64

In [ ]:
reviews[pd.isnull(reviews.country)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery,critic,index_backwards
913,NaN,"Amber in color, this wine has aromas of peach ...",Asureti Valley,87,30.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Gotsa Family Wines 2014 Asureti Valley Chinuri,Chinuri,Gotsa Family Wines,everyone,9087
3131,NaN,"Soft, fruity and juicy, this is a pleasant, si...",Partager,83,NaN,NaN,NaN,NaN,Roger Voss,@vossroger,Barton & Guestier NV Partager Red,Red Blend,Barton & Guestier,everyone,6869
4243,NaN,"Violet-red in color, this semisweet wine has a...",Red Naturally Semi-Sweet,88,18.0,NaN,NaN,NaN,Mike DeSimone,@worldwineguys,Kakhetia Traditional Winemaking 2012 Red Natur...,Ojaleshi,Kakhetia Traditional Winemaking,everyone,5757
9509,NaN,This mouthwatering blend starts with a nose of...,Theopetra Malagouzia-Assyrtiko,92,28.0,NaN,NaN,NaN,Susan Kostrzewa,@suskostrzewa,Tsililis 2015 Theopetra Malagouzia-Assyrtiko W...,White Blend,Tsililis,everyone,491
9750,NaN,This orange-style wine has a cloudy yellow-gol...,Orange Nikolaevo Vineyard,89,28.0,NaN,NaN,NaN,Jeff Jenssen,@worldwineguys,Ross-idi 2015 Orange Nikolaevo Vineyard Chardo...,Chardonnay,Ross-idi,everyone,250

In [ ]:
reviews.region_2.fillna("Unknown")

0                 Unknown
1                 Unknown
2       Willamette Valley
3                 Unknown
4       Willamette Valley
              ...
9995               Sonoma
9996      Columbia Valley
9997              Unknown
9998                 Napa
9999              Unknown
Name: region_2, Length: 10000, dtype: object

In [ ]:
reviews.taster_twitter_handle.replace("@kerinokeefe", "@kerino")

0           @kerino
1        @vossroger
2       @paulgwine
3               NaN
4       @paulgwine
           ...
9995            NaN
9996    @paulgwine
9997     @vossroger
9998            NaN
9999     @vossroger
Name: taster_twitter_handle, Length: 10000, dtype: object

# Quiz

1. Which column has the most null values?